# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "wistia-api"
  s.version = "0.1.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jim Bancroft", "Mark Bates", "Christian W\u{f6}rner"]
  s.date = "2012-05-06"
  s.description = "A ruby library for working with Wistia's data API."
  s.email = "kri@exelab.eu"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/config.rb",
    "lib/wistia.rb",
    "lib/wistia/base.rb",
    "lib/wistia/config.rb",
    "lib/wistia/embed.rb",
    "lib/wistia/media.rb",
    "lib/wistia/project.rb",
    "lib/wistia/projects/sharing.rb",
    "spec/spec_helper.rb",
    "spec/support/config.test.yml",
    "spec/support/local_config.rb",
    "spec/wistia/base_spec.rb",
    "spec/wistia/embed_spec.rb",
    "spec/wistia/projects/sharing_spec.rb",
    "spec/wistia_spec.rb",
    "wistia-api.gemspec"
  ]
  s.homepage = "http://github.com/kr1/wistia-api"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Ruby wrapper for Wistia's API"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activeresource>, ["~> 3.1.1"])
      s.add_runtime_dependency(%q<configatron>, [">= 2.6.4"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_runtime_dependency(%q<activeresource>, [">= 3.2.0"])
      s.add_runtime_dependency(%q<configatron>, [">= 2.6.4"])
    else
      s.add_dependency(%q<activeresource>, ["~> 3.1.1"])
      s.add_dependency(%q<configatron>, [">= 2.6.4"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.0"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<activeresource>, [">= 3.2.0"])
      s.add_dependency(%q<configatron>, [">= 2.6.4"])
    end
  else
    s.add_dependency(%q<activeresource>, ["~> 3.1.1"])
    s.add_dependency(%q<configatron>, [">= 2.6.4"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.0"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<activeresource>, [">= 3.2.0"])
    s.add_dependency(%q<configatron>, [">= 2.6.4"])
  end
end

